### ISSUE TITLE
esta nos seus planos atualizar pro terraform 0.12 ?

### ISSUE THREAD

**Issue by rafilkmp3** [msfidelis/ecs-pipeline#3]
Seria irado ver isso no terraform 0.12

**Comment by msfidelis** [comment]
Tenho planos de migrar, com certeza! Estou esperando a versão 0.12.* ficar mais stable e o pessoal começar a usar mais. Mas estou migrando as poucos conforme os bug fixes da hashicorp vão surgindo. A branch é essa: https://github.com/msfidelis/ecs-pipeline/tree/terraform_0.12
