### ISSUE TITLE
terraform 0.12 compability

### ISSUE THREAD

**Issue by thespamer** [msfidelis/ecs-pipeline#9]
Please update this for terraform 0.12, I've tried to convert using 0.12upgrade but no success.

**Comment by thespamer** [comment]
https://github.com/thespamer/ecs-v12

**Comment by msfidelis** [comment]
Check this project. This is a incremental evolution from `ecs-pipeline` running on Terraform 0.12 with support for multi-clusters and multi-services

https://github.com/msfidelis/ecs-microservices-orchestration
